# Generated by Django 3.2.6 on 2022-04-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
